[package]
name = "rustcms-app"
description = "Rust CMS: Application"
resolver = "3"
edition.workspace = true
version.workspace = true
keywords.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
