[package]
name = "srv-macros"
description = "Rust CMS: Server macros"
version = "0.0.1"
edition = "2024"
resolver = "3"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.100", features = ["full", "extra-traits"] }
quote = { version = "1.0.40" }
proc-macro2 = { version = "1.0.95" }